Binus/Models/Assessment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Binus.Models
{
    public class Assessment
    {
        public int assessmentID { get; set; }
        public int assessmentTypeID { get; set; }
        public int transactionID { get; set; }
        public string assessmentTitle { get; set; }
        public string assessmentDescription { get; set; }
        public string assessmentType { get; set; }
        public string createdBy { get; set; }
        public string lastUpdate { get; set; }
    }
}

Binus/Models/AssessmentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Binus.Models
{
    public class AssessmentType
    {
        public int assessmentTypeID { get; set; }
        public string assessmentType { get; set; }
    }
}

Binus/Controllers/Api/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Binus.Data;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Binus.Models.AssessmentProcrasiantor;
using Binus.Models.AssessmentIntelligence;
using Binus.Models.AssessmentSensory;
using Binus.Models;
using System.Web;
using System.Security.Claims;

namespace Binus.Controllers.Api
{
    [Authorize]
    public class AssessmentController : ApiController
    {
        BinusEntities db = new BinusEntities();

        [Authorize(Roles = "student")]
        [HttpGet]
        public AssessmentType getCurrentAssessmentType(int id)
        {
            var result = (from transaction in db.Transactions1
                          join assessment in db.Assessments1 on transaction.AssessmentID equals assessment.AssessmentID
                          join assessmentType in db.AssessmentTypes1 on assessment.AssessmentTypeID equals assessmentType.AssessmentTypeID
                          where transaction.TransactionID == id
                          select new AssessmentType {
                              assessmentTypeID = assessmentType.AssessmentTypeID,
                              assessmentType = assessmentType.AssessmentType
                          }).FirstOrDefault();

            return result;
        }


        [Authorize(Roles = "student")]
        [HttpPost]
        public HttpResponseMessage postResultAssessmentSensory(AssessmentSensory model)
        {
            var identity = (ClaimsIdentity)User.Identity;

            foreach (var value in model.sensories)
            {
                ResultAssessments resultAssessment = new ResultAssessments();
                resultAssessment.TransactionID = model.transactionID;
                resultAssessment.ResultWord = value.sensory;
                resultAssessment.ResultAssessmentID = value.sensoryValue;

                db.ResultAssessments1.Add(resultAssessment);
                db.SaveChanges();
            }

            Transactions studentTransaction = (from transaction in db.Transactions1
                                               where transaction.Username == identity.Name
                                               select transaction).FirstOrDefault();

            studentTransaction.Status = "finish";
            db.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }


        [Authorize(Roles = "student")]
        [HttpPost]
        public HttpResponseMessage postResultAssessmentProcrasinator(AssessmentProcrasinator model)
        {
            var identity = (ClaimsIdentity)User.Identity;

            IEnumerable<ScoreProcrasinator> scoreProcrasinators = (from transaction in db.Transactions1
                                                                   join assessment in db.Assessments1 on transaction.AssessmentID equals assessment.AssessmentID
                                                                   join assessmenProcrasinator in db.AssessmentProcrasinators1 on assessment.AssessmentID equals assessmenProcrasinator.AssessmentID
                                                                   join scoreProcrasinator in db.ScoreProcrasinators1 on assessmenProcrasinator.AssessmentProcrasinatorID equals scoreProcrasinator.AssessmentProcrasinatorID
                                                                   select new ScoreProcrasinator {
                                                                       scoreWord = scoreProcrasinator.ScoreWord,
                                                                       startValue = scoreProcrasinator.StartValue,
                                                                       endValue = scoreProcrasinator.EndValue
                                                                   }).ToList();
            foreach (ScoreProcrasinator scoreProcrasinator in scoreProcrasinators)
            {
                if (model.countScore >= scoreProcrasinator.startValue &&
                    model.countScore <= scoreProcrasinator.endValue)
                {
                    ResultAssessments resultAssessment = new ResultAssessments();
                    resultAssessment.ResultWord = scoreProcrasinator.scoreWord;
                    resultAssessment.ResultValue = model.countScore;
                    resultAssessment.TransactionID = model.transactionID;

                    db.ResultAssessments1.Add(resultAssessment);
                    db.SaveChanges();
                    break;
                }
            }


            Transactions studentTransaction = (from transaction in db.Transactions1
                                               where transaction.Username == identity.Name
                                               select transaction).FirstOrDefault();
            studentTransaction.Status = "finish";
            db.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }


        [Authorize(Roles = "student")]
        [HttpPost]
        public HttpResponseMessage postResultAssessmentIntelligence(AssessmentIntelligence model)
        {
            var identity = (ClaimsIdentity)User.Identity;

            foreach (var value in model.statementIntelligences)
            {
                ResultAssessments resultAssessment = new ResultAssessments();
                resultAssessment.ResultWord = value.statementIntelligence;
                resultAssessment.ResultValue = value.countStatementIntelligence;
                resultAssessment.TransactionID = model.transactionID;

                db.ResultAssessments1.Add(resultAssessment);
                db.SaveChanges();
            }

            Transactions studentTransaction = (from transaction in db.Transactions1
                                               where transaction.Username == identity.Name
                                               select transaction).FirstOrDefault();
            studentTransaction.Status = "finish";
            db.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }



        [HttpGet]
        public AssessmentIntelligence getCurrentAssessmentIntelligence(int assessmentID) {
            var result = (from assessment in db.Assessments1
                          join assessmentIntelligence in db.AssessmentIntelligences1 on assessment.AssessmentID equals assessmentIntelligence.AssessmentID
                          where assessment.AssessmentID == assessmentID
                          select new AssessmentIntelligence
                          {
                              assessmentIntelligenceID = assessmentIntelligence.AssessmentIntelligenceID,
                              assessmentTitle = assessment.AssessmentTitle,
                              assessmentDescription = assessment.AssessmentDescription,
                              scoreIntelligences = (from scoreIntelligence in db.ScoreIntelligences1
                                                    where scoreIntelligence.AssessmentIntelligenceID == assessmentIntelligence.AssessmentIntelligenceID
                                                    select new ScoreIntelligence
                                                    {
                                                        scoreIntelligenceID = scoreIntelligence.ScoreIntelligenceID,
                                                        scoreValue = scoreIntelligence.ScoreValue,
                                                        scoreWord = scoreIntelligence.ScoreWord
                                                    }).ToList(),
                              statementIntelligences = (from statementIntelligence in db.StatementIntelligences1
                                                        where statementIntelligence.AssessmentIntelligenceID == assessmentIntelligence.AssessmentIntelligenceID
                                                        select new StatementIntelligence
                                                        {
                                                            statementIntelligenceID = statementIntelligence.StatementIntelligenceID,
                                                            statementIntelligence = statementIntelligence.StatementIntelligence,
                                                            statementDetailIntelligences = (from statementDetailIntelligence in db.StatementDetailIntelligences1
                                                                                            where statementDetailIntelligence.StatementIntelligenceID == statementIntelligence.StatementIntelligenceID
                                                                                            select new StatementDetailIntelligence
                                                                                            {
                                                                                                statementDetailIntelligenceID = statementDetailIntelligence.StatementDetailIntelligenceID,
                                                                                                statementDetailIntelligence = statementDetailIntelligence.StatementDetailIntelligence
                                                                                            }).ToList()
                                                        }).ToList()
                          }).FirstOrDefault();

            return result;
        }


        [HttpGet]
        public AssessmentSensory getCurrentAssessmentSensory(int assessmentID)
        {
            var result = (from assessment in db.Assessments1
                          join assessmentSensory in db.AssessmentSensories1 on assessment.AssessmentID equals assessmentSensory.AssessmentID
                          where assessment.AssessmentID == assessmentID

Binus/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Binus.Controllers
{
    [Authorize]
    public class AssessmentController : Controller
    {
        [Authorize(Roles ="admin")]
        public ActionResult ManageAll()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult UpdateAssessment()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult AddAssessment()
        {
            return View();
        }

        [Authorize(Roles = "student")]
        public ActionResult Manage()
        {
            return View();
        }

        [Authorize(Roles = "student")]
        public ActionResult ShowAssessment()
        {
            return View();
        }

        [Authorize(Roles = "student")]
        public ActionResult ResultPage()
        {
            return View();
        }
    }
}

Binus/Views/Assessment/Manage.cshtml
@{
    ViewBag.Title = "Binus University";
}

@section css
{
    <link rel="stylesheet" type="text/css" href="~/Content/css/AddAssessment.css">
}

<div class="site-content" id="site-content">
    <section class="breadcrumb">
        <div class="container">
            <div class="wrap">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Assessment</a></li>
                    <li>Manage Assessment</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="page-heading">
        <div class="container">
            <h1>Manage Assessment</h1>
        </div>
    </section>

    <div class="main-content has-widget" id="main-content">
        <div class="container">
            <div class="box-container">
                <div class="single-content popup-content" id="target-id">
                    <div class="page-sub-heading">
                        <div class="row" style="height:30px;">
                            <div class="column">
                                <h2 id="page" class="page-heading" style="line-height:40px;">Assessment</h2>
                            </div>
                        </div>
                    </div>

                    <div class="freeze-pane" style="overflow-y : hidden !important">
                        <table class="bordered zebra" id="assessment-table">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>TITLE</th>
                                    <th>TYPE</th>
                                    <th>TRANSACTION DATE</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody id="assessment-container">
                                <tr class="template assessment" style="display:none;">
                                    <td class="assessment-no">XX</td>
                                    <td class="assessment-title">XX</td>
                                    <td class="assessment-type">XX</td>
                                    <td class="assessment-transaction-date">XX</td>
                                    <td class="assessment-action">
                                        <span style="display:none;" class="assessment-do">
                                            <i class="icon-button icon-edit button-do-assessment"></i>
                                            <span class="transaction-id" style="display: none">XX</span>
                                        </span>
                                        <span style="display:none;" class="assessment-view">
                                            <i class="icon-button icon-view button-view-assessment"></i>
                                            <span class="transaction-id" style="display: none">XX</span>
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="popup-content-dialog" id="popup_confirmation" style="display:none;">
    <form>
        <p>Save confirmation</p>
        <div class="action" style="text-align:center;">
            <a href="#" class="button button-primary" id="button_yes">Yes</a>
            <a href="#" class="button button-primary" id="button_no">No</a>
        </div>
    </form>
</div>


@section scripts
{
    <script type="text/javascript">

        const assessmentContainer=$("#assessment-container");
        const dataTable=$("#assessment-table");

        $(document).ready(function() {

            $.ajaxSetup({
                headers: { "Authorization": "Bearer "+sessionStorage.getItem("access_token") }
            });

            $.ajax({
                method: "GET",
                url: "/api/transaction/getUserTransaction",
                beforeSend: function() {
                    dataTable.DataTable().clear();
                    $.fancybox("#popup_loading");
                },
                success: function(data) {
                    parent.$.fancybox.close();
                    data.forEach(function(value) {
                        let template=assessmentContainer.find(".template").first();
                        template=template.clone();
                        template.removeClass("template");
                        template.show();

                        template.find(".assessment-no").text(assessmentContainer.find(".assessment").length);
                        template.find(".assessment-title").text(value.assessmentTitle);
                        template.find(".assessment-type").text(value.assessmentType);
                        template.find(".assessment-transaction-date").text(value.transactionDate);
                        template.find(".transaction-id").text(value.transactionID);
                        if(value.status==="finish") {
                            template.find(".assessment-view").show();
                        }
                        else {
                            template.find(".assessment-do").show();
                        }

                        assessmentContainer.append(template);
                        dataTable.DataTable().rows.add(template);

                    });
                    dataTable.DataTable().columns.adjust().draw();
                    assessmentContainer.find(".template").remove();
                }
            });
        });


        $(document).on("click",".button-do-assessment",function() {
            let currentAssessment=$(this).parents(".assessment");
            let transactionID=currentAssessment.find(".transaction-id").first().text();

            localStorage.setItem("transactionID",transactionID);
            window.location.href="/assessment/ShowAssessment";
        });

        $(document).on("click",".button-view-assessment",function() {
            let currentAssessment=$(this).parents(".assessment");
            let transactionID=currentAssessment.find(".transaction-id").first().text();

            localStorage.setItem("transactionID",transactionID);
            window.location.href="/assessment/ResultPage";
        });


        $('.freeze-pane').binus_freeze_pane({
            fixed_left: 1,
            fixed_right: 0,
            height: 300
        });
    </script>
}

Binus/Views/Assessment/ManageAll.cshtml
@{
    ViewBag.Title = "Binus University";
}

@section css
{
    <link rel="stylesheet" type="text/css" href="~/Content/css/AddAssessment.css">
}

<div class="site-content" id="site-content">
    <section class="breadcrumb">
        <div class="container">
            <div class="wrap">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Assessment</a></li>
                    <li>Manage Assessment</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="page-heading">
        <div class="container">
            <h1>Manage Assessment</h1>
        </div>
    </section>

    <div class="main-content has-widget" id="main-content">
        <div class="container">
            <div class="box-container">
                <div class="single-content popup-content" id="target-id">
                    <div class="page-sub-heading">
                        <div class="row" style="height:30px;">
                            <div class="column two-thirds ">
                                <h2 id="page" class="page-heading" style="line-height:40px;">Assessment</h2>
                            </div>
                            <div class="column one-third">
                                <p style="float:right;">
                                    <a href="@Url.Action("AddAssessment", "Assessment")" class="button button-primary" id="button_add">Add Assessment</a>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="freeze-pane" style="overflow-y : hidden !important">
                        <table class="bordered zebra" id="assessment-table">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>TITLE</th>
                                    <th>TYPE</th>
                                    <th>TRANSACTION DATE</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody id="assessment-container">
                                <tr class="template assessment" style="display:none;">
                                    <td class="assessment-no">XX</td>
                                    <td class="assessment-title">XX</td>
                                    <td class="assessment-type">XX</td>
                                    <td class="assessment-transaction-date">XX</td>
                                    <td class="assessment-action">
                                        <span class="assessment-edit">
                                            <i class="icon-button icon-edit button-edit-assessment"></i>
                                            <span class="assessment-id" style="display: none">XX</span>
                                        </span>
                                        <span class="assessment-delete">
                                            <i class="icon-button icon-trash button-delete-assessment"></i>
                                            <span class="assessment-id" style="display: none">XX</span>
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@RenderPage("~/Views/Shared/Popup/PopupConfirmation.cshtml")


@section scripts
{
    <script type="text/javascript">

        const assessmentContainer=$("#assessment-container");
        const dataTable=$("#assessment-table");

        $(document).ready(function() {
            $.ajaxSetup({
                headers: { "Authorization": "Bearer "+sessionStorage.getItem("access_token") }
            });

            $.ajax({
                method : "GET",
                url : "/api/assessment/getAllAssessment",
                beforeSend: function() {
                    dataTable.DataTable().clear();
                },
                success: function(data) {
                    data.forEach(function(value) {
                        let template=assessmentContainer.find(".template").first();
                        template=template.clone();
                        template.removeClass("template");
                        template.show();

                        template.find(".assessment-no").text(assessmentContainer.find(".assessment").length);
                        template.find(".assessment-title").text(value.assessmentTitle);
                        template.find(".assessment-type").text(value.assessmentType);
                        template.find(".assessment-transaction-date").text(value.lastUpdate);
                        template.find(".assessment-id").text(value.assessmentID);
                        assessmentContainer.append(template);
                        dataTable.DataTable().rows.add(template);
                    });
                    dataTable.DataTable().columns.adjust().draw();
                    assessmentContainer.find(".template").remove();
                }
            });
        });


        $(document).on("click",".button-edit-assessment",function() {
            let currentAssessment = $(this).parents(".assessment");
            let assessmentID = currentAssessment.find(".assessment-id").first().text();
            
            localStorage.setItem("assessmentID",assessmentID);
            window.location.href="/assessment/UpdateAssessment";
        });

        $(document).on("click",".button-delete-assessment",function() {
            let currentAssessment=$(this).parents(".assessment");
            currentAssessment.addClass("selected");
            let assessmentID=currentAssessment.find(".assessment-id").first().text();
            $.ajax({
                method : "DELETE",
                url : "/api/assessment/deleteAssessment",
                data : {
                    assessmentID : assessmentID
                },
                success: function(){
                    dataTable.DataTable().rows(".selected").remove().draw();
                },
                error : function(){
                    currentAssessment.removeClass("selected");
                }
            });
        });

        $('.freeze-pane').binus_freeze_pane({
            fixed_left: 1,
            fixed_right: 0,
            height: 300
        });
    </script>
}

Binus/Views/Assessment/ResultPage.cshtml
@{
    /**/
    ViewBag.Title = "Binus University";
}

@section css
{
    <link rel="stylesheet" type="text/css" href="~/Content/css/result.css">
}

<div class="main-content has-widget" id="main-content">
    <div class="container">
        <div class="box-container">
            <div class="single-content popup-content" id="target-id">
                <div id="assessment-container">
                    <h1 class="tk-title current-username"></h1>
                    <blockquote>
                        <h3 class="role-title">Your Result</h3>
                        <h1 class="tk-title assessment-result"></h1>
                        <h3 class="role-description" id="descriptionTest"></h3>
                        <h3 class="tambahan"></h3>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        const assessmentContainer = $("#assessment-container");

        $(document).ready(function() {
            $.ajaxSetup({
                headers: { "Authorization": "Bearer "+sessionStorage.getItem("access_token") }
            });
            
            $.ajax({
                method: "GET",
                url: "/api/result/getCurrentResultAssessment",
                data: {
                    id : localStorage.getItem("transactionID")
                },
                success: function(data) {
                    let currentUsername = data[0].fullname;
                    assessmentContainer.find(".current-username").text("THANKS, " + currentUsername);
                    assessmentContainer.find(".assessment-result").text(data[0].resultWord);

                    if(data.length!=1) {
                        data.shift();
                        data.forEach(function(result) {
                            assessmentContainer.find(".assessment-result").text(assessmentContainer.find(".assessment-result").text()+" & "+result.resultWord);
                        });
                    }
                }
            });
        });
    </script>
}